const districts = [
    { value: "bandarban", label: "Bandarban" },
    { value: "barguna", label: "Barguna" },
    { value: "barishal", label: "Barishal" },
    { value: "bhola", label: "Bhola" },
    { value: "bogura", label: "Bogura" },
    { value: "brahmanbaria", label: "Brahmanbaria" },
    { value: "chandpur", label: "Chandpur" },
    { value: "chapai_nawabganj", label: "Chapai Nawabganj" },
    { value: "chattogram", label: "Chattogram" },
    { value: "chuadanga", label: "Chuadanga" },
    { value: "comilla", label: "Comilla" },
    { value: "coxsbazar", label: "Cox's Bazar" },
    { value: "dhaka", label: "Dhaka" },
    { value: "dinajpur", label: "Dinajpur" },
    { value: "faridpur", label: "Faridpur" },
    { value: "feni", label: "Feni" },
    { value: "gaibandha", label: "Gaibandha" },
    { value: "gazipur", label: "Gazipur" },
    { value: "gopalganj", label: "Gopalganj" },
    { value: "habiganj", label: "Habiganj" },
    { value: "jamalpur", label: "Jamalpur" },
    { value: "jashore", label: "Jashore" },
    { value: "jhalokathi", label: "Jhalokathi" },
    { value: "jhenaidah", label: "Jhenaidah" },
    { value: "joypurhat", label: "Joypurhat" },
    { value: "khagrachari", label: "Khagrachari" },
    { value: "khulna", label: "Khulna" },
    { value: "kishoreganj", label: "Kishoreganj" },
    { value: "kurigram", label: "Kurigram" },
    { value: "kushtia", label: "Kushtia" },
    { value: "lakshmipur", label: "Lakshmipur" },
    { value: "lalmonirhat", label: "Lalmonirhat" },
    { value: "madaripur", label: "Madaripur" },
    { value: "magura", label: "Magura" },
    { value: "manikganj", label: "Manikganj" },
    { value: "meherpur", label: "Meherpur" },
    { value: "moulvibazar", label: "Moulvibazar" },
    { value: "munshiganj", label: "Munshiganj" },
    { value: "mymensingh", label: "Mymensingh" },
    { value: "naogaon", label: "Naogaon" },
    { value: "narail", label: "Narail" },
    { value: "narayanganj", label: "Narayanganj" },
    { value: "narsingdi", label: "Narsingdi" },
    { value: "natore", label: "Natore" },
    { value: "netrokona", label: "Netrokona" },
    { value: "nilphamari", label: "Nilphamari" },
    { value: "noakhali", label: "Noakhali" },
    { value: "pabna", label: "Pabna" },
    { value: "panchagarh", label: "Panchagarh" },
    { value: "patuakhali", label: "Patuakhali" },
    { value: "pirojpur", label: "Pirojpur" },
    { value: "rajbari", label: "Rajbari" },
    { value: "rajshahi", label: "Rajshahi" },
    { value: "rangamati", label: "Rangamati" },
    { value: "rangpur", label: "Rangpur" },
    { value: "satkhira", label: "Satkhira" },
    { value: "shariatpur", label: "Shariatpur" },
    { value: "sherpur", label: "Sherpur" },
    { value: "sirajganj", label: "Sirajganj" },
    { value: "sunamganj", label: "Sunamganj" },
    { value: "sylhet", label: "Sylhet" },
    { value: "tangail", label: "Tangail" },
    { value: "thakurgaon", label: "Thakurgaon" }
  ];
  
  export default districts;
  