const districtUpazilas = [
   
      { value: "keraniganj", label: "Keraniganj" },
      { value: "dohar", label: "Dohar" },
      { value: "narayanganj", label: "Narayanganj" },
      { value: "sonargaon", label: "Sonargaon" },
      { value: "savar", label: "Savar" },
      { value: "dhamrai", label: "Dhamrai" },
      { value: "manikganj", label: "Manikganj" },
      { value: "munshiganj", label: "Munshiganj" },
      { value: "tangail", label: "Tangail" },
      { value: "madaripur", label: "Madaripur" },
      { value: "shariatpur", label: "Shariatpur" },
      { value: "narsingdi", label: "Narsingdi" },
      { value: "kishoreganj", label: "Kishoreganj" },
      { value: "gazipur", label: "Gazipur" },
 
      { value: "anwara", label: "Anwara" },
      { value: "banshkhali", label: "Banshkhali" },
      { value: "boalkhali", label: "Boalkhali" },
      { value: "chandanaish", label: "Chandanaish" },
      { value: "fatikchhari", label: "Fatikchhari" },
      { value: "hathazari", label: "Hathazari" },
      { value: "lohagara", label: "Lohagara" },
      { value: "mirsharai", label: "Mirsharai" },
      { value: "patiya", label: "Patiya" },
      { value: "rangunia", label: "Rangunia" },
      { value: "sandwip", label: "Sandwip" },
      { value: "satkania", label: "Satkania" },
      { value: "chandpur", label: "Chandpur" },
      { value: "cumilla", label: "Cumilla" },
      { value: "meghna", label: "Meghna" },
      { value: "laksam", label: "Laksam" },
 
      { value: "dacope", label: "Dacope" },
      { value: "koyra", label: "Koyra" },
      { value: "paikgachha", label: "Paikgachha" },
      { value: "batiaghata", label: "Batiaghata" },
      { value: "dumuria", label: "Dumuria" },
      { value: "keshabpur", label: "Keshabpur" },
      { value: "rupsha", label: "Rupsha" },
      { value: "kusumgram", label: "Kusumgram" },
      { value: "mongla", label: "Mongla" },
      { value: "shyamnagar", label: "Shyamnagar" },
      { value: "ashashuni", label: "Ashashuni" },
      { value: "tala", label: "Tala" },
      { value: "dighalia", label: "Dighalia" },
      { value: "phultala", label: "Phultala" },
      { value: "bagerhat", label: "Bagerhat" },
  
  
      { value: "bagmara", label: "Bagmara" },
      { value: "charghat", label: "Charghat" },
      { value: "puthia", label: "Puthia" },
      { value: "tanore", label: "Tanore" },
      { value: "shibganj", label: "Shibganj" },
      { value: "mohanpur", label: "Mohanpur" },
      { value: "durgapur", label: "Durgapur" },
      { value: "rajshahi", label: "Rajshahi" },
      { value: "naogaon", label: "Naogaon" },
  
      { value: "agailjhara", label: "Agailjhara" },
      { value: "babuganj", label: "Babuganj" },
      { value: "barishal", label: "Barishal" },
      { value: "gournadi", label: "Gournadi" },
      { value: "hijla", label: "Hijla" },
      { value: "kaukhali", label: "Kaukhali" },
      { value: "wazirpur", label: "Wazirpur" },
      { value: "bakerganj", label: "Bakerganj" },
      { value: "muladi", label: "Muladi" },

      { value: "bishwanath", label: "Bishwanath" },
      { value: "companiganj", label: "Companiganj" },
      { value: "fenchuganj", label: "Fenchuganj" },
      { value: "gopalganj", label: "Gopalganj" },
      { value: "jaintiapur", label: "Jaintiapur" },
      { value: "kanaighat", label: "Kanaighat" },
      { value: "moulvibazar", label: "Moulvibazar" },
      { value: "osmaninagar", label: "Osmaninagar" },
      { value: "rajnagar", label: "Rajnagar" },
      { value: "south-surma", label: "South Surma" },
      { value: "sunamganj", label: "Sunamganj" },
      { value: "dakkhin-sunamganj", label: "Dakkhin Sunamganj" },
  
      { value: "badarganj", label: "Badarganj" },
      { value: "gangachara", label: "Gangachara" },
      { value: "kaunia", label: "Kaunia" },
      { value: "mithapukur", label: "Mithapukur" },
      { value: "pirganj", label: "Pirganj" },
      { value: "rangpur", label: "Rangpur" },
      { value: "rohonpur", label: "Rohonpur" },
      { value: "taraganj", label: "Taraganj" },

      { value: "bhaluka", label: "Bhaluka" },
      { value: "gaffargaon", label: "Gaffargaon" },
      { value: "fulbaria", label: "Fulbaria" },
      { value: "haluaghat", label: "Haluaghat" },
      { value: "mymensingh", label: "Mymensingh" },
      { value: "nandail", label: "Nandail" },
      { value: "phulpur", label: "Phulpur" },
      { value: "trishal", label: "Trishal" }
]

  
  export default districtUpazilas;